apiVersion: v1
kind: Service
metadata:
  name: cgateway
  namespace: demo
  labels:
    app: cgateway
spec:
  selector:
    app: cgateway
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
